name: Host System Builder

on:
  push:
  pull_request:


jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: actions/setup-python@v3.1.0
      with:
        python-version: '3.9.x'
    - run: pip install meson ninja scan-build
    - run: brew install ccache cppcheck
    - run: scan-build meson setup build
      env:
        CC: ccache gcc-10
    - run: cppcheck --project=build/compile_commands.json
    - run: scan-build meson compile -C build
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v3.1.0
      with:
        python-version: '3.9.x'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: ccache

    - run: pip install meson ninja
    - run: meson setup build
      env:
        CC: ccache gcc
    - run: meson compile -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: build/meson-logs/testlog.txt

  ubuntu_linux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/ubuntu-host:latest"
    steps:
    - uses: actions/checkout@v2.3.2
    - run: |
        meson setup build &&
        cppcheck --project=build/compile_commands.json &&
        meson compile -C build
      working-directory: .
 
  debian_linux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/debian-host:latest"
    steps:
    - uses: actions/checkout@v2.3.2
    - run: |
        meson setup build &&
        cppcheck --project=build/compile_commands.json &&
        meson compile -C build
      working-directory: .
  fedora_linux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/fedora-host:latest"
    steps:
    - uses: actions/checkout@v2.3.2
    - run: |
        meson setup build &&
        cppcheck --project=build/compile_commands.json &&
        meson compile -C build
      working-directory: .
  arch_linux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/archlinux-host:latest"
    steps:
    - uses: actions/checkout@v2.3.2
    - run: |
        meson setup build &&
        cppcheck --project=build/compile_commands.json &&
        meson compile -C build
      working-directory: .
  opensuse_linux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/opensuse-host:latest"
    steps:
    - uses: actions/checkout@v2.3.2
    - run: |
        meson setup build &&
        cppcheck --project=build/compile_commands.json &&
        meson compile -C build
      working-directory: .
